config/routes.rb
VotaPrato::Application.routes.draw do

  resources :comentarios

	resources :cursos

  resources :clientes

  resources :qualificacoes

	resources :restaurantes

	match "/" => "restaurantes#index"

	match "/comentarios/remover/:id" => "comentarios#destroy", :as => "remover_comentario"

end

app/models/cliente.rb
#encoding = UTF-8

class Cliente < ActiveRecord::Base
  validates_presence_of			:nome,
														:message => "O cliente precisa ter um nome!"

  validates_uniqueness_of		:nome,
														:message => "Xiii esse nome já está cadastrado!"

  validates_numericality_of	:idade,
														:greater_than => 0,
														:less_than => 100,
														:message => "A idade do cliente precisa ser entre 0 e 100"

  has_many :qualificacoes
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.xml
  def index
    @clientes = Cliente.order("id").paginate :page=> params['page'], :per_page => 3

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.xml
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.xml
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.xml
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to(@cliente, :notice => 'Cliente was successfully created.') }
        format.xml  { render :xml => @cliente, :status => :created, :location => @cliente }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cliente.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.xml
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to(@cliente, :notice => 'Cliente was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cliente.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.xml
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to(clientes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :idade %><br />
    <%= f.text_field :idade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<!-- Box -->
<div class="box">
	<!-- Box Head -->
	<div class="box-head">
		<h2 class="left">Clientes Cadastrados</h2>
		<div class="right">
			<label>Procurar Clientes</label>
			<input type="text" class="field small-field" />
			<input type="submit" class="button" value="search" />
		</div>
	</div>
	<!-- End Box Head -->	

	<!-- Table -->
	<div class="table">
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
			<tr>
				<th width="13"><input type="checkbox" class="checkbox" /></th>
				<th width="200">Nome</th>
				<th>Idade</th>
				<th>Data do cadastro</th>
				<th width="120" class="ac">Ações</th>
			</tr>
			<% @clientes.each do |cliente| %>
				<tr class='link <%= cycle("odd", "even") %>'>
					<td><input type="checkbox" class="checkbox" /></td>
					<td><h3><%= link_to cliente.nome, cliente_path(cliente), :class => "link" %></h3></td>
					<td><%= cliente.idade %></td>
					<td><%= formata_data(cliente.created_at) %></td>
					<td class="acoes">
							<%= link_to 'Destroy', cliente, :confirm => 'Are you sure?', :method => :delete, :class => "ico del" %>
							<%= link_to 'Edit', edit_cliente_path(cliente), :class => "ico edit" %>
					</td>
				</tr>
			<% end %>
		</table>

		<br clear="all" />
		<%= link_to content_tag(:span, "Criar novo cliente"), new_cliente_path, :class => "add-button" %>
		<br clear="all" />

		<!-- Pagging -->
		<div class="pagging">
			<div class="left"><%= page_entries_info @clientes %></div>
			<div class="right"><%= will_paginate @clientes %></div>
		</div>
		<!-- End Pagging -->
		
	</div>
	<!-- Table -->

	
</div>
<!-- End Box -->

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cliente.nome %>
</p>

<p>
  <b>Idade:</b>
  <%= @cliente.idade %>
</p>

<%= link_to "Nova Qualificação", :controller => "qualificacoes", :action => "new", :cliente => @cliente %>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>