config/routes.rb
VotaPrato::Application.routes.draw do

  resources :comentarios

	resources :cursos

  resources :clientes

  resources :qualificacoes

	resources :restaurantes

	match "/" => "restaurantes#index"

	match "/comentarios/remover/:id" => "comentarios#destroy", :as => "remover_comentario"

end

app/models/restaurante.rb
#encoding=UTF-8

class Restaurante < ActiveRecord::Base
	validates_presence_of :nome, :message => "O nome deve ser preenchido"
	validates_presence_of :endereco, :message => "O endereço deve ser preenchido"
	validates_presence_of :especialidade, :message => "Especialidade deve ser preenchido"

	validates_uniqueness_of	:nome, :message => "O nome já está cadastrado"
	validates_uniqueness_of	:endereco, :message => "O endereço já está cadastrado"

	validate :primeira_lestra_deve_ser_maiuscula

	private
	def primeira_lestra_deve_ser_maiuscula
		errors.add("nome", "A primeira letra do nome deve ser maiúscula") unless nome =~ /[A-Z].*/
	end

	has_many	:qualificacoes
	has_many	:comentarios, :as => :comentavel
	has_and_belongs_to_many :pratos

	scope :massas, where(:especialidade => "Comida Italiana")
	scope :atuais, where('created_at > ?', 3.months.ago)

end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController

	def index
		@restaurantes = Restaurante.order("nome").paginate :page=> params['page'], :per_page => 3
	end

	def show
		@restaurante = Restaurante.find(params[:id])
		respond_to do |format|
			format.html
			format.xml	{ render :xml		=> @restaurante }
			format.json	{ render :json	=> @restaurante }
		end
	end

	def new
		@restaurante = Restaurante.new
	end

	def	create
		@restaurante = Restaurante.new(params[:restaurante])
		if @restaurante.save
			flash[:notice] = "O restaurante #{@restaurante.nome} Foi Criado com sucesso!"
			redirect_to(:action => "show", :id => @restaurante)
		else
			render :action => "new"
		end
	end

	def edit
		@restaurante = Restaurante.find(params[:id])
	end

	def update
		@restaurante = Restaurante.find(params[:id])
		if @restaurante.update_attributes(params[:restaurante])
			redirect_to :action => 'show', :id => @restaurante
		else
			render :action => "edit"
		end
	end

	def destroy
		@restaurante = Restaurante.find(params[:id])
		@restaurante.destroy
		redirect_to(:action => "index")
	end

end

app/views/restaurantes/_form.html.erb
<% form_for :restaurante, :url => { :action => action, :id => @restaurante } do |f| %>
	<div class="form">
		<p>
			<%= f.label :nome %>
			<%= f.text_field :nome, :class => "field size1" %>
		</p>
		<p>
			<%= f.label :endereco %>
			<%= f.text_field :endereco, :class => "field size1" %>
		</p>
		<p>
			<%= f.label :especialidade %>
			<%= f.text_field :especialidade, :class => "field size1" %>
		</p>
		<!-- Form Buttons -->
			<div class="buttons">
				<%= submit_tag button, :class => "button" %>
			</div>
		<!-- End Form Buttons -->
	</div>
<% end %>

app/views/restaurantes/edit.html.erb
<% if @restaurante.errors.any? %>
	<ul>
		<% @restaurante.errors.each do |campo, msg| %>
			<li><%= campo %> - <%= msg %></li>
		<% end %>
	</ul>
<% end %>

<!-- Box -->
<div class="box">
	<!-- Box Head -->
	<div class="box-head"><h2>Editando o Restaurante - <%= @restaurante.nome %></h2></div>
	<!-- End Box Head -->
	<%= render :partial => "form", :locals => { :action =>  "edit", :button => "Atualizar" } %>

	<br clear="all" />	
	<%= link_to content_tag(:span, "Voltar"), {:action => "index"}, :class => "add-button" %>
	<br clear="all" />
	<br clear="all" />
</div>
<!-- End Box -->

app/views/restaurantes/index.html.erb
<!-- Box -->
<div class="box">
	<!-- Box Head -->
	<div class="box-head">
		<h2 class="left">Restaurantes Cadastrados</h2>
		<div class="right">
			<label>Procurar Restaurantes</label>
			<input type="text" class="field small-field" />
			<input type="submit" class="button" value="search" />
		</div>
	</div>
	<!-- End Box Head -->	

	<!-- Table -->
	<div class="table">
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
			<tr>
				<th width="13"><input type="checkbox" class="checkbox" /></th>
				<th width="200">Nome</th>
				<th>Data</th>
				<th>Especialidade</th>
				<th width="160" class="ac">Ações</th>
			</tr>
			<% @restaurantes.each do |restaurante| %>
				<tr class='link <%= cycle("odd", "even") %>'>
					<td><input type="checkbox" class="checkbox" /></td>
					<td><h3><%= link_to restaurante.nome, restaurante_path(restaurante), :class => "link" %></h3></td>
					<td><%= formata_data(restaurante.created_at) %></td>
					<td><%= restaurante.especialidade %></td>
					<td class="acoes">

			<%= link_to "Ver comentários", restaurante_path(restaurante), :class => "ico comment", :id => "iframe" %>
			<%= link_to "Editar", edit_restaurante_path(restaurante), :class => "ico edit" %>
					</td>
				</tr>
			<% end %>
		</table>

		<br clear="all" />
		<%= link_to content_tag(:span, "Criar novo restaurante"), { :action => "new" }, :class => "add-button" %>
		<br clear="all" />

		<!-- Pagging -->
		<div class="pagging">
			<div class="left"><%= page_entries_info @restauranetes %></div>
			<div class="right"><%= will_paginate @restauranetes %></div>
		</div>
		<!-- End Pagging -->
		
	</div>
	<!-- Table -->

	
</div>
<!-- End Box -->

app/views/restaurantes/new.html.erb
<% if @restaurante.errors.any? %>
<!-- Message Error -->
<div class="msg msg-form">
	<div>
		<ul>
			<% @restaurante.errors.each do |campo, msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
</div>
<!-- End Message Error -->
<% end %>

<!-- Box -->
<div class="box">
	<!-- Box Head -->
	<div class="box-head"><h2>Adicionando um novo restaurante</h2></div>
	<!-- End Box Head -->
	<%= render :partial => "form", :locals => { :action =>  "create", :button => "Criar" } %>
</div>
<!-- End Box -->

app/views/restaurantes/show.html.erb
<% unless @restaurante.comentarios.empty? %>
	<%= comentarios @restaurante %>
<% end %>