config/routes.rb
VotaPrato::Application.routes.draw do

  resources :comentarios

	resources :cursos

  resources :clientes

  resources :qualificacoes

	resources :restaurantes

	match "/" => "restaurantes#index"

	match "/comentarios/remover/:id" => "comentarios#destroy", :as => "remover_comentario"

end

app/controllers/qualificacoes_controller.rb
class QualificacoesController < ApplicationController
  # GET /qualificacoes
  # GET /qualificacoes.xml
  def index
    @qualificacoes = Qualificacao.order("id").paginate :page=> params['page'], :per_page => 3

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @qualificacoes }
    end
  end

  # GET /qualificacoes/1
  # GET /qualificacoes/1.xml
  def show
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @qualificacao }
    end
  end

  # GET /qualificacoes/new
  # GET /qualificacoes/new.xml
  def new
    @qualificacao = Qualificacao.new
		@qualificacao.cliente = Cliente.find(params[:cliente]) if params[:cliente]

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @qualificacao }
    end
  end

  # GET /qualificacoes/1/edit
  def edit
    @qualificacao = Qualificacao.find(params[:id])
  end

  # POST /qualificacoes
  # POST /qualificacoes.xml
  def create
    @qualificacao = Qualificacao.new(params[:qualificacao])

    respond_to do |format|
      if @qualificacao.save
        format.html { redirect_to(@qualificacao, :notice => 'Qualificacao was successfully created.') }
        format.xml  { render :xml => @qualificacao, :status => :created, :location => @qualificacao }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @qualificacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /qualificacoes/1
  # PUT /qualificacoes/1.xml
  def update
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      if @qualificacao.update_attributes(params[:qualificacao])
        format.html { redirect_to(@qualificacao, :notice => 'Qualificacao was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @qualificacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /qualificacoes/1
  # DELETE /qualificacoes/1.xml
  def destroy
    @qualificacao = Qualificacao.find(params[:id])
    @qualificacao.destroy

    respond_to do |format|
      format.html { redirect_to(qualificacoes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/qualificacoes_helper.rb
module QualificacoesHelper
end

app/views/qualificacoes/_form.html.erb
<%= form_for(@qualificacao) do |f| %>
  <% if @qualificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qualificacao.errors.count, "error") %> prohibited this qualificacao from being saved:</h2>

      <ul>
      <% @qualificacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

	<% if @qualificacao.cliente %>
		<%= f.hidden_field "cliente_id" %>
	<% else %>
		<div class="field">	
			<%= f.label :cliente_id %><br />
			<%=
				f.collection_select(	:cliente_id,
															Cliente.order("nome"),
															:id,
															:nome,
															{:prompt => true}
														)
			%>
		</div>
	<% end%>


	<% if @qualificacao.restaurante %>
		<%= f.hidden_field "restaurante_id" %>
	<% else %>
		<div class="field">
		  <%= f.label :restaurante_id %><br />
			<%=
				f.collection_select(	:restaurante_id,
															Restaurante.order("nome"),
															:id,
															:nome,
															{:prompt => true}
														)
			%>
		</div>
	<% end%>


  <div class="field">
    <%= f.label :nota %><br />
    <%= f.text_field :nota %>
  </div>
  <div class="field">
    <%= f.label :valor_gasto %><br />
    <%= f.text_field :valor_gasto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qualificacoes/edit.html.erb
<h1>Editing qualificacao</h1>

<%= render 'form' %>

<%= link_to 'Show', @qualificacao %> |
<%= link_to 'Back', qualificacoes_path %>

app/views/qualificacoes/index.html.erb
<!-- Box -->
<div class="box">
	<!-- Box Head -->
	<div class="box-head">
		<h2 class="left">Qualificações Cadastradas</h2>
		<div class="right">
			<label>Procurar Qualificações</label>
			<input type="text" class="field small-field" />
			<input type="submit" class="button" value="search" />
		</div>
	</div>
	<!-- End Box Head -->	

	<!-- Table -->
	<div class="table">
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
			<tr>
				<th width="13"><input type="checkbox" class="checkbox" /></th>
				<th width="200">Cliente</th>
				<th>Restaurante</th>
				<th>Nota</th>
				<th>Valor gasto</th>
				<th width="160" class="ac">Ações</th>
			</tr>
			<% @qualificacoes.each do |qualificacao| %>
				<tr class='link <%= cycle("odd", "even") %>'>
					<td><input type="checkbox" class="checkbox" /></td>
					<td><h3><%= qualificacao.cliente.nome %></h3></td>
					<td><%= qualificacao.restaurante.nome %></td>
					<td><%= qualificacao.nota %></td>
					<td><%= qualificacao.valor_gasto %></td>
					<td class="acoes">
							<%= link_to 'Edit', edit_qualificacao_path(qualificacao), :class => "ico edit" %>
							<%= link_to 'Show', qualificacao, :class => "ico hide link" %>
							<%= link_to 'Destroy', qualificacao, :confirm => 'Are you sure?', :method => :delete, :class => "ico del" %>

					</td>
				</tr>
			<% end %>
		</table>

		<br clear="all" />
		<%= link_to content_tag(:span, "Criar nova Qualificação"), new_qualificacao_path, :class => "add-button" %>
		<br clear="all" />

		<!-- Pagging -->
		<div class="pagging">
			<div class="left"><%= page_entries_info @qualificacoes %></div>
			<div class="right"><%= will_paginate @qualificacoes %></div>
		</div>
		<!-- End Pagging -->
	</div>
	<!-- Table -->
</div>
<!-- End Box -->

app/views/qualificacoes/new.html.erb
<h1>New qualificacao</h1>

<%= render 'form' %>

<%= link_to 'Back', qualificacoes_path %>

app/views/qualificacoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cliente:</b>
  <%= @qualificacao.cliente.nome %>
</p>

<p>
  <b>Restaurante:</b>
  <%= @qualificacao.restaurante.nome %>
</p>

<p>
  <b>Nota:</b>
  <%= @qualificacao.nota %>
</p>

<p>
  <b>Valor gasto:</b>
  <%= @qualificacao.valor_gasto %>
</p>


<%= link_to 'Edit', edit_qualificacao_path(@qualificacao) %> |
<%= link_to 'Back', qualificacoes_path %>

<% unless @qualificacao.comentarios.empty? %>
	<%= comentarios @qualificacao %>
<% end %>

<%= novo_comentario(@qualificacao) %>